name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up OCaml environment
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.14.2

      - name: Initialize opam
        run: |
          opam init -y
          eval $(opam env)

      - name: Install dependencies
        run: |
          eval $(opam env)
          opam install dune menhir llvm.14.0.6 ppx_deriving odoc

      - name: Build project
        run: |
          eval $(opam env)
          dune build